version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 3

  dispatcher:
    build:
      context: .
      dockerfile: Dispatcher/Dockerfile
    container_name: dispatcher
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RabbitMQ__Uri=amqp://rabbitmq:5672
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:5000"

  consumer:
    build:
      context: .
      dockerfile: Consumer/Dockerfile
    container_name: consumer
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RabbitMQ__Uri=amqp://rabbitmq:5672
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:5001"

  integration-tests:
    build:
      context: .
      dockerfile: IntegrationTests/Dockerfile
    depends_on:
      - dispatcher
      - consumer
      - rabbitmq

volumes:
  rabbitmq_data:
